### ISSUE TITLE
Çözünürlük Problemi Redmi Note 9 Pro 

### ISSUE THREAD

**Issue by Mehmet-I** [symbuzzer/livebootmagisk#1]
Merhaba Ali Bey,

Görüntü biraz geniş olduğu için yazıların başları ve sonları çerçeve dışında kalıyor. Bunun için yapılabilecek bir şey var mıdır?

İyi günler.

**Comment by symbuzzer** [comment]
Merhaba, wrap seçeneği var aslında uygulamada. Muhtemelen kernel erken boot işleminde ekran çözünürlüğünü ayarlamıyor. Bu uygulamadan ya da modülden kaynaklı bir sorun değil. Muhtemelen kullandığın rom veya kernelden kaynaklı bir durum. Başka romlarda dene istersen...

**Comment by Mehmet-I** [comment]
Önceki eea romdu. Şimdi miui eu rom'a geçtim. İkisinde de aynı sorunu yaşadım. Yapacak bir şey yok o halde :) Teşekkürler.

**Comment by symbuzzer** [comment]
Anladım, benim test ettiğim cihazlarda sorun olmadı. Video atabilirsen anlamaya çalışayım

**Comment by Mehmet-I** [comment]
> Anladım, benim test ettiğim cihazlarda sorun olmadı. Video atabilirsen anlamaya çalışayım

https://github.com/symbuzzer/livebootmagisk/assets/63732211/fa8e6ec6-febd-40bb-9533-e3fe0cdece30

Bu şekilde geniş bir görüntü var. Sağ soldan kırpılmış gibi.

**Comment by symbuzzer** [comment]
Yok bu normal olan. Satır yetmediğinde alttaki satır geçmiş, dikkatli bak. Bazı satırlar anlamlı başlamış, o satıra sığmayınca devamı alt satıra geçmiş.

**Comment by Mehmet-I** [comment]
> Yok bu normal olan. Satır yetmediğinde alttaki satır geçmiş, dikkatli bak. Bazı satırlar anlamlı başlamış, o satıra sığmayınca devamı alt satıra geçmiş. @Mehmet-I

Peki buna yapılacak bir şey var mı küçültebilmek için yazıları.

**Comment by symbuzzer** [comment]
@Mehmet-I  var ama bu sefer alt satıra geçmesi gereken yazılar hiç görünmeyecek. öyle de saçma olmuyor mu? Yazıların küçülme olayı yok
